name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # <--- THIS STOPS ONE ERROR FROM KILLING EVERYTHING
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # <--- UPDATED TO STOP THE WARNINGS
      - name: Install Deps
        run: npm install
      - name: Build & Upload
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
